version: '3.1'

services:
  corewebapp:
    image: corewebapp:debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports: 
      - "8084:80"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    volumes: 
      - ./obj/Docker/publish/:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro