version: '2'

services:
  build:
    image: microsoft/aspnetcore-build:1
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore  && dotnet publish corewebapp.csproj -c Release -o ./obj/Docker/publish"

